# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "first-app"
client_id = "63f5144c037a8512ceb89a0c90033b69"
application_url = "https://portfolio-southwest-whereas-reunion.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://portfolio-southwest-whereas-reunion.trycloudflare.com/auth/callback",
  "https://portfolio-southwest-whereas-reunion.trycloudflare.com/auth/shopify/callback",
  "https://portfolio-southwest-whereas-reunion.trycloudflare.com/api/auth/callback",
  "https://portfolio-southwest-whereas-reunion.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mdpabel.myshopify.com"
